// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://demvahfvucyfyllprrqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlbXZhaGZ2dWN5ZnlsbHBycnFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDUwMjYsImV4cCI6MjA1OTUyMTAyNn0.FJB3TS_u1uRjF_ctBGuHkKs7B8-vG0TalDjHLFMFTxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);